apiVersion: v1
kind: Secret
metadata:
  name: kuest-app-secrets
  namespace: kuest
type: Opaque
stringData:
  SUPABASE_URL: replace-me
  BETTER_AUTH_SECRET: replace-me
  CRON_SECRET: replace-me
  POSTGRES_URL: replace-me
  SUPABASE_SERVICE_ROLE_KEY: replace-me
  KUEST_ADDRESS: replace-me
  KUEST_API_KEY: replace-me
  KUEST_API_SECRET: replace-me
  KUEST_PASSPHRASE: replace-me
  ADMIN_WALLETS: replace-me
  NEXT_PUBLIC_REOWN_APPKIT_PROJECT_ID: replace-me
